### ISSUE TITLE
`info` command to retrieve meta information

### ISSUE THREAD

**Issue by apnadkarni** [apnadkarni/tcl-cffi#57]
- [ ] `info function declaration` - returns the function declaration
- [ ] `info function syntax` - calling syntax for function
- [ ] `info struct declaration` - returns struct declaration
- [ ] Get rid of struct describe
- [ ] `info alias declaration`
- [ ] `info prototype`
- [ ] `help X` Looks for X among functions, structs, aliases, prototypes and displays syntax and declaration
